### PR TITLE
Add examples/

### PR DESCRIPTION
**Pull request by Vincentimetr**

### CODE REVIEW

**Comment by Vincentimetr** [comment]
https://gitlab.com/Vincentimetr/sqf_linter

**Comment by Vincentimetr** [comment]
It miss some examples in this project...

**Comment by jonpas** [comment]
This PR needs work, spaces around operators would be a good start.

**Comment by jonpas** [comment]
I didn't take a closer look, pycodestyle (pr other linters) should give everything.

**Comment by Vincentimetr** [comment]
@jonpas 
Here an example of the result:

https://vincentimetr.gitlab.io/sqf_linter/problems.html

It is an automation linter on a gitlab project that show errors at every push with Spinx documentation

**Comment by jonpas** [comment]
Oh, I was talking purely about the code in this pull request. It is missing spaces around operators, new lines before function definitions.

I am not sure if that examples generator fits this project, seems to be better as a separate extension - but that's up to @LordGolias to decide.

**Comment by LordGolias** [comment]
I agree that this is not suitable for this project and should be placed somewhere else. The thing we care is having a CLI tool for the linter and a API to use for custom use-cases.

**Pull request closed without merging**
